#!/bin/sh

rm -f allFunctions.sed

echo "  Extraction all functions"

# for f in `ls -1 refManual/class*Vec*-members.html`
for f in `ls -1 refManual/class*-members.html`
do
  name=`echo $f | sed s:"refManual/class\(.*\)-members.html":"\1": | sed s:qglviewer_._.::`
  grep "^[ 	]*<tr" $f | grep -v "enum value" | grep -v "enum name" | grep -v "operator" > /tmp/allFunctions
  sed s:"^[^>]*><td><a class=\"el\" href=\"\([^>]*>\)\([^<]*\)</a>(.*":"\2 \1 $name":g /tmp/allFunctions | grep -v "^ *<tr" >> allFunctions.sed
  # sed s:"^[^>]*><td><a class=\"el\" \([^>]*>\)\([^<]*\)</a>.*":"s§$name\:\:\2(\\\\([^)]*\\\\))§<a \1$name\:\:\2(\\\\1)</a>§g":g /tmp/allFunctions >> allFunctions.sed
  # sed s:"^[^>]*><td><a class=\"el\" \([^>]*>\)\([^<]*\)</a>.*":"s§\\\\([^\:][^\:]\\\\)\2(\\\\([^)]*\\\\))§\\\\1<a \1\2(\\\\2)</a>§g":g /tmp/allFunctions >> allFunctions.sed
done

sort allFunctions.sed > /tmp/allFunctions
awk '{ if ($1!=prev) print "s§\\([^:][^:]\\)"$1"(\\([^)]*\\))§\\1<a href=\"#PATH#"$2$1"(\\2)</a>§g"; print "s§"$3"::"$1"(\\([^)]*\\))§<a href=\"#PATH#"$2$3"::"$1"(\\1)</a>§g"; prev=$1; }' /tmp/allFunctions > allFunctions.sed
