name: libQGLViewer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: 'ubuntu-latest'
            qtVersion: '6.2.2'
          - runner: 'ubuntu-latest'
            qtVersion: '5.15.2'
#          - runner: 'macOS-11'
#            qtVersion: '6.2.2'
          - runner: 'windows-2019'
            qtVersion: '6.2.2'
            qtArch: 'win64_msvc2019_64'
          - runner: 'windows-2019'
            qtVersion: '5.15.2'
            qtArch: 'win64_msvc2019_64'
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qtVersion }}
          arch: ${{ matrix.qtArch }}
          cache: true
          
      - name: Install GLU
        if: startsWith(matrix.runner, 'ubuntu')
        run: sudo apt-get install -y libglu1-mesa-dev          

      - name: Build QGLViewer
        run: |
           mkdir build
           cmake -B build -S .
           cmake --build build --config Release
